name: Build assignemnts.pdf document

on:
  push:
    paths:
      - 'assignments/**'
      - '.github/workflows/build_assignments.yml'
  pull_request:
    branches:
      - 'current'
      - 'future-*'

jobs:

  fetch_sources:
    runs-on: ubuntu-latest
    steps:

      - name: Initialize
        uses: actions/checkout@v2

      - name: Upload sources
        uses: actions/upload-artifact@v3
        with:
          name: sources
          path: assignments

  delete_previous_release:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:

      - name: Delete previous release (if any)
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          delete_release: true

  build_document_parts:
    runs-on: ubuntu-latest
    needs: ['fetch_sources']
    strategy:
      matrix:
        part: ['session1', 'session2', 'session3', 'session4']
    steps:

      - name: Download sources
        uses: actions/download-artifact@v3

      - name: Build LaTeX document parts
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ matrix.part }}.tex
          working_directory: sources

      - name: Upload LaTeX document part
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.part }}
          path: sources/${{ matrix.part }}.pdf

  merge_document_parts:
    runs-on: ubuntu-latest
    needs: ['build_document_parts', 'delete_previous_release']
    if: github.event_name != 'pull_request'
    steps:

      - name: Download sources and LaTeX document parts
        uses: actions/download-artifact@v3

      - name: Prepare directory structure
        run: |
            for i in 1 2 3 4
            do
              mv "session$i/session$i.pdf" "sources/"
            done

      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: sources

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: sources/main.pdf
          asset_name: assignments.pdf
          asset_content_type: pdf
