name: Create future branch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 9 *'

jobs:

  create_future_branch:

    name: Create future branch
    runs-on: ubuntu-latest
    if: github.repository_owner == 'BMCV'

    permissions:
      contents: write

    steps:

      - name: Initialize
        uses: actions/checkout@v4

      - name: Create and initialize future branch
        uses: kostrykin/create-future-branch-action@master
        with:
          init: python .github/init-future-branch.py